In [19]:
import numpy as np
from sklearn.decomposition import PCA
import pandas as pd

In [20]:
X1 = np.array([2,5,1,6,8,3,4,7,9,10])
X2 = 2*X1
X3 = 0.1*X2
X4 = 0.1*X1
X5 = 0.01*X1

In [21]:
data = pd.DataFrame({'X1':X1,'X2':X2, 'X3':X3, 'X4':X4, 'X5':X5})
data.head()

X1  X2   X3   X4    X5
0   2   4  0.4  0.2  0.02
1   5  10  1.0  0.5  0.05
2   1   2  0.2  0.1  0.01
3   6  12  1.2  0.6  0.06
4   8  16  1.6  0.8  0.08

# Without Any Standardization

In [22]:
 pca = PCA(n_components=5)
 pca.fit(data)

PCA(n_components=5)

In [23]:
pca.explained_variance_ratio_

array([1.00000000e+00, 6.10808432e-33, 1.42907825e-34, 8.76850157e-37,
       3.80902191e-66])

In [24]:
pca.components_

array([[-4.44989754e-01, -8.89979507e-01, -8.89979507e-02,
        -4.44989754e-02, -4.44989754e-03],
       [-8.93558674e-01,  4.48612134e-01, -1.44075775e-02,
        -7.20378874e-03, -6.36993472e-03],
       [ 5.90869425e-02,  8.17533214e-02, -8.89758743e-01,
        -4.44879372e-01, -1.53899534e-02],
       [ 6.76372920e-03, -1.55515312e-04,  1.41832607e-02,
         7.09163034e-03, -9.99851375e-01],
       [ 0.00000000e+00, -1.10289667e-17, -4.47213595e-01,
         8.94427191e-01, -1.95679557e-15]])

In [25]:
pca.components_.shape

(5, 5)

# Mean-centered

In [26]:
mc_data = pd.DataFrame()
mc_data['X1'] = data['X1'] - data.X1.mean()
mc_data['X2'] = data['X2'] - data.X2.mean()
mc_data['X3'] = data['X3'] - data.X3.mean()
mc_data['X4'] = data['X4'] - data.X4.mean()
mc_data['X5'] = data['X5'] - data.X5.mean()
mc_data.head()

X1   X2   X3    X4     X5
0 -3.5 -7.0 -0.7 -0.35 -0.035
1 -0.5 -1.0 -0.1 -0.05 -0.005
2 -4.5 -9.0 -0.9 -0.45 -0.045
3  0.5  1.0  0.1  0.05  0.005
4  2.5  5.0  0.5  0.25  0.025

In [27]:
mc_data.describe()

X1         X2            X3            X4            X5
count  10.00000  10.000000  1.000000e+01  1.000000e+01  1.000000e+01
mean    0.00000   0.000000 -2.220446e-17 -1.110223e-17 -5.551115e-18
std     3.02765   6.055301  6.055301e-01  3.027650e-01  3.027650e-02
min    -4.50000  -9.000000 -9.000000e-01 -4.500000e-01 -4.500000e-02
25%    -2.25000  -4.500000 -4.500000e-01 -2.250000e-01 -2.250000e-02
50%     0.00000   0.000000  0.000000e+00  0.000000e+00 -6.938894e-18
75%     2.25000   4.500000  4.500000e-01  2.250000e-01  2.250000e-02
max     4.50000   9.000000  9.000000e-01  4.500000e-01  4.500000e-02

In [28]:
 pca = PCA(n_components=5)
 pca.fit(mc_data)

PCA(n_components=5)

In [29]:
pca.explained_variance_ratio_

array([1.00000000e+00, 6.10831915e-33, 1.47521609e-34, 2.36391877e-37,
       7.64642697e-66])

# Standardized

In [30]:
st_data = pd.DataFrame()
st_data['X1'] = (data['X1'] - data.X1.mean())/ data.X1.std()
st_data['X2'] = (data['X2'] - data.X2.mean())/ data.X2.std()
st_data['X3'] = (data['X3'] - data.X3.mean())/ data.X3.std()
st_data['X4'] = (data['X4'] - data.X4.mean())/ data.X4.std()
st_data['X5'] = (data['X5'] - data.X5.mean())/ data.X5.std()
st_data.head()

X1        X2        X3        X4        X5
0 -1.156012 -1.156012 -1.156012 -1.156012 -1.156012
1 -0.165145 -0.165145 -0.165145 -0.165145 -0.165145
2 -1.486301 -1.486301 -1.486301 -1.486301 -1.486301
3  0.165145  0.165145  0.165145  0.165145  0.165145
4  0.825723  0.825723  0.825723  0.825723  0.825723

In [31]:
st_data.describe()

X1         X2            X3            X4            X5
count  10.000000  10.000000  1.000000e+01  1.000000e+01  1.000000e+01
mean    0.000000   0.000000 -4.440892e-17 -4.440892e-17 -1.776357e-16
std     1.000000   1.000000  1.000000e+00  1.000000e+00  1.000000e+00
min    -1.486301  -1.486301 -1.486301e+00 -1.486301e+00 -1.486301e+00
25%    -0.743151  -0.743151 -7.431505e-01 -7.431505e-01 -7.431505e-01
50%     0.000000   0.000000  0.000000e+00  0.000000e+00 -2.220446e-16
75%     0.743151   0.743151  7.431505e-01  7.431505e-01  7.431505e-01
max     1.486301   1.486301  1.486301e+00  1.486301e+00  1.486301e+00

In [32]:
 pca = PCA(n_components=5)
 pca.fit(st_data)

PCA(n_components=5)

In [33]:
pca.explained_variance_ratio_

array([1.00000000e+00, 1.11492015e-32, 4.99532710e-33, 1.05702174e-33,
       1.70119136e-65])